// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5132.Nick;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.VictorSP;
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static VictorSP driveTrainVictorSP1;
    public static VictorSP driveTrainVictorSP2;
    public static VictorSP driveTrainVictorSP3;
    public static VictorSP driveTrainVictorSP4;
    public static CANTalon chainCANTalon1;
	public static RobotDrive DRIVE_TRAIN_ROBOT_DRIVE_2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainVictorSP1 = new VictorSP(0);
        LiveWindow.addActuator("DriveTrain", "VictorSP 1", driveTrainVictorSP1);
        
        driveTrainVictorSP2 = new VictorSP(1);
        LiveWindow.addActuator("DriveTrain", "VictorSP 2", driveTrainVictorSP2);
        
        driveTrainVictorSP3 = new VictorSP(2);
        LiveWindow.addActuator("DriveTrain", "VictorSP 3", driveTrainVictorSP3);
        
        driveTrainVictorSP4 = new VictorSP(3);
        LiveWindow.addActuator("DriveTrain", "VictorSP 4", driveTrainVictorSP4);
        
        chainCANTalon1 = new CANTalon(4);
        LiveWindow.addActuator("Chain", "Cantalon 1", chainCANTalon1);
        
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
